const propertyKeywords: string[] = [
    "recommend",
    "suggest",
    "best project",
    "any good property",
    "which one do you suggest",
    "show another",
    "different project",
    "next project",
    "utilities cost",
    "another one",
    "any other options",
    "what else do you recommend?",
    "another recommendation",
    "current listing",
    "price range",
    "any vacant units",
    "nearby amenities",
    "schedule a tour",
    "360-degree home tour",
    "what is the asking price",
    "how old is the property",
    "how close is public transport",
    "which schools are nearby",
    "what are the amenities",
    "are pets allowed",
    "floor plan",
    "what is the tenure",
    "completion year",
    "highlights",
    "facilities",
    "developer",
    "built",
    "pet-friendly",
    "schedule a viewing",
    "contact",
    "video",
    "location",
    "exact location",
    "maintenance",
    "how many units",
    "project detail",
    "interior",
    "description",
    "virtual tour",
    "property available",
    "nearest",
    "nearby",
    "public transportation"
  ];
  
  export default propertyKeywords;
  